### ISSUE TITLE
Unable to lectures of ERA

### ISSUE THREAD

**Issue by nilsreichardt** [Valentin-Metz/tum_video_scraper#10]
I'm able to download the lectures of [EidI](https://live.rbg.tum.de/course/2022/W/eidi), [DS](https://live.rbg.tum.de/course/2022/W/DS) and [PGdP](https://live.rbg.tum.de/course/2022/W/pgdpzue). However, I'm not able to download the lectures of [ERA](https://live.rbg.tum.de/course/2022/W/WiSe22ERA).

Error:
```
reni@lxhalle:~/Desktop/tum_video_scraper$ python3 src/main.py -c config.yaml 
Starting new run!

Scanning TUM-live:
Traceback (most recent call last):
  File "/u/halle/reni/home_at/Desktop/tum_video_scraper/src/main.py", line 151, in <module>
    tum_live.get_subjects(tum_live_subjects, username, password, videos_for_subject)
  File "/u/halle/reni/home_at/Desktop/tum_video_scraper/src/tum_live.py", line 71, in get_subjects
    m3u8_playlists = get_video_links_of_subject(driver, subjects_identifier, camera_type)
  File "/u/halle/reni/home_at/Desktop/tum_video_scraper/src/tum_live.py", line 50, in get_video_links_of_subject
    filename = driver.find_element(By.XPATH, "/html/body/div[5]/div/div[3]/div/div[1]/h1").text.strip()
  File "/u/halle/reni/home_at/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/u/halle/reni/home_at/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/u/halle/reni/home_at/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[5]/div/div[3]/div/div[1]/h1"}
  (Session info: headless chrome=109.0.5414.74)
Stacktrace:
#0 0x563e9341f763 <unknown>
#1 0x563e931f5be7 <unknown>
#2 0x563e93231a22 <unknown>
#3 0x563e93231b31 <unknown>
#4 0x563e9326b894 <unknown>
#5 0x563e93251acd <unknown>
#6 0x563e932695aa <unknown>
#7 0x563e93251873 <unknown>
#8 0x563e93224f52 <unknown>
#9 0x563e932260be <unknown>
#10 0x563e9346baf6 <unknown>
#11 0x563e9346e66b <unknown>
#12 0x563e9346eeba <unknown>
#13 0x563e93454ebe <unknown>
#14 0x563e9346f63c <unknown>
#15 0x563e93446b08 <unknown>
#16 0x563e9348da98 <unknown>
#17 0x563e9348dc35 <unknown>
#18 0x563e934a8145 <unknown>
#19 0x7fd4358ecb43 <unknown>
```

```
TUM-live:
  "ERA": "2022/W/WiSe22ERA:COMB"

Username: "..."
Password: "..."

Output-Folder: "./output"

Maximum-Parallel-Downloads: 3
```

Used commit 7ee0b43176f6da4506915c03e866e51bbe16be5a

**Comment by Valentin-Metz** [comment]
Fixed in c3f5979fca1dd604242d865d9f19547fd14dba07.
