### ISSUE TITLE
Error `ValueError: too many values to unpack (expected 2)` when downloading videos

### ISSUE THREAD

**Issue by nilsreichardt** [Valentin-Metz/tum_video_scraper#11]
I'm trying the lectures of ERA, but I'm getting the following error:

```
user@lxhalle:~/Desktop/tum_video_scraper$ python3 src/main.py -c config.yaml 
Starting new run!

Scanning TUM-live:
Found 40 videos for "ERA"

--------------------

Starting downloads:
Traceback (most recent call last):
  File "/u/halle/user/home_at/Desktop/tum_video_scraper/src/main.py", line 199, in <module>
    main()
  File "/u/halle/user/home_at/Desktop/tum_video_scraper/src/main.py", line 192, in main
    for subject, playlists in videos_for_subject:
ValueError: too many values to unpack (expected 2)
```

My `config.yaml`:
```
TUM-live:
  "ERA": "2022/W/WiSe22ERA:COMB"

Username: "..."
Password: "..."

Output-Folder: "./output"

Maximum-Parallel-Downloads: 3
```

Use commit 2e21e5c804c7c97b4a8164c62f76c19cded5b138

**Comment by Valentin-Metz** [comment]
Fixed in e0b676732f5adc01addae791db72e3717a4d7713.
